modLoader="javafml"
loaderVersion="[37,)"
license="Academic Free License v3.0"

[[mods]]
modId="moneymod"
version="1.0.0"
displayName="MoneyMod"
credits=""
displayURL="https://artcas2-mc.alwaysdata.net/download/moneymod"
authors="Artcas2"
description='''
Ajoute de l'agent au jeu.
'''

[[dependencies.moneymod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1]"
    ordering="NONE"
    side="BOTH"




